import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { cloakSSROnlySecret } from "ssr-only-secrets";

import { TRPCReactProvider } from "~/trpc/react";
import { cookies } from "next/headers";

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const encryptedCookiePromise = Promise.resolve(cookies()).then((cookies) => {
    return cloakSSROnlySecret(cookies.toString(), "SECRET_KEY_VAR");
  })
  return (
    <html lang="en">
      <body className={GeistSans.className}>
        <TRPCReactProvider cookiePromise={encryptedCookiePromise}>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
